on:
  workflow_dispatch:
    inputs:
      deploy_to_env:
        description: 'Deploy to ENV'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - test
        - qa

jobs:
  update_test_images:
    if: ${{ inputs.deploy_to_env == 'test' || inputs.deploy_to_env == 'all'}}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: | 
          echo "test"

  update_qa_images:
    if: ${{ inputs.deploy_to_env == 'qa' || inputs.deploy_to_env == 'all' }}
    runs-on: ubuntu-latest
    steps:
      - name: qa
        run: | 
          echo "QA"
